# Generated by Django 6.0.2 on 2026-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='demo_file',
            field=models.FileField(blank=True, null=True, upload_to='demo_files/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='game_files/'),
        ),
    ]
